cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'puma/puma'
tap 'caskroom/fonts'

cask 'xquartz'

brew 'ack'
brew 'coreutils'
brew 'go'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'jq'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'puma/puma/puma-dev'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'unrar'
brew 'wget'
brew 'yarn'
brew 'neovim'
brew 'ffmpeg'
brew 'git'
brew 'awscli'
brew 'fzf'
brew 'pyenv-virtualenvwrapper'

cask '1password'
cask 'google-chrome'
cask 'slack'
cask 'docker'
cask 'captain'
cask 'iterm2'
cask 'font-fira-code'
cask 'font-source-code-pro-for-powerline'
cask 'spotify'
