cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'puma/puma'
tap 'madebymany/custom'

cask 'xquartz'

brew 'ack'
brew 'coreutils'
brew 'go'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'jq'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'puma/puma/puma-dev'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'unrar'
brew 'wget'
brew 'yarn'
brew 'neovim'
brew 'appalling'
brew 'ffmpeg'
brew 'git'
brew 'imagemagick'
brew 'moltar'

cask '1password'
cask 'firefox'
cask 'google-chrome'
cask 'handbrake'
cask 'slack'
cask 'vlc'
