update
upgrade
tap caskroom/cask
tap homebrew/dupes
tap madebymany/custom
cask install xquartz
install appalling
install brew-cask
install ffmpeg
install git
install imagemagick
install moltar
install node
install openssl
install postgresql
install python
install reattach-to-user-namespace
install zshi
install neovim
cleanup
